### ISSUE TITLE
Error launching with rolling

### ISSUE THREAD

**Issue by scpeters** [jacobperron/pc_pipe#7]
I am seeing an error saying `TypeError: __init__() missing 1 required keyword-only argument: 'executable'` when attempting to launch `bringup.launch.xml`. It's coming from [stereo_image_proc.launch.py:53](https://github.com/jacobperron/pc_pipe/blob/b5cf867cf95286ee6f9748795b233016b7704595/launch/stereo_image_proc.launch.py#L53). I think this may be caused by https://github.com/ros2/launch_ros/pull/197

**Comment by jacobperron** [comment]
Fixed in https://github.com/jacobperron/pc_pipe/commit/10366ca70c1199ad6e8b93d2ac1ae00c1a29dfbe
